### ISSUE TITLE
[Dataset] Submitting the SPOLIN dataset for ConvoKit

### ISSUE THREAD

**Issue by wise-east** [CornellNLP/ConvoKit#158]
Hello, I would like to have the SPOLIN dataset from [Grounding Conversations with Improvised Dialogues (ACL 2020)](https://justin-cho.com/spolin) added to ConvoKit. 

All the requested information according to the [contribution guidelines](https://github.com/CornellNLP/ConvoKit/blob/a012fb07968b4f0ab811c3a3789a597f9239f821/CONTRIBUTING.md) can be found here: https://drive.google.com/drive/folders/1XjwgEh38N-9MwNwAy1icpMYFMlvUzl_u?usp=sharing 

Let me know if you need any help from my part to get this dataset added. Thank you!

**Comment by wise-east** [comment]
@cristiandnm Hello Cristian! let me know if there is anything I can help to get this dataset included into ConvoKit :)

**Comment by cristiandnm** [comment]
Thanks for the dataset and for contributing it to ConvoKit!  One minor thing that would be good to change before we include it: I notice that as of now there are only two speakers in the dataset, which can be a bit confusing and might conflict with the intended use of the corpus hierarchy (implying that 2 speakers generated all utterances.  Could you create a unique pair of users for each conversation (e.g., speaker_43245_1, speaker_43245_2, where 43245 is the conversation id)?

Let me know if that makes sense.

Cristian

**Comment by wise-east** [comment]
Yes, that makes sense. I made the update according to your suggestions (e.g., speaker_43245_1, speaker_43245_2, where 43245 is the conversation id)

**Comment by calebchiam** [comment]
@wise-east Sorry for the delay, we've been busy developing other features for ConvoKit. We'll be adding the dataset today. Could you update the SPOLIN description you shared re: how speakers are named?

Seems confusing at the moment. Some pairs are suffixed by '0' or '1', while others are suffixed by '1', '2'. Is this deliberate?

<img width="1100" alt="image" src="https://user-images.githubusercontent.com/14286996/175383316-955459af-bf4c-470d-93d0-78276cc15a7b.png">

**Comment by wise-east** [comment]
@calebchiam Hi Caleb. I've updated the description. Sorry for the confusion. All of them should be 0 and 1 for the first and second turns respectively, but for the validation set there was a bug that made them 1 and 2 instead. 

I don't have access to the code base that formatted the dataset for the time being, so is it possible that you could simply make this fix for the speaker row such that valid_x_p_1 becomes valid_x_p_0 and valid_x_r_2 becomes valid_x_r_1? If not, I'll make the fix later when I have access and notify you then.

**Comment by calebchiam** [comment]
@wise-east Added comments on your Google doc, but it looks like there are some other issues, so please address those and I'll come back to this later. Thanks!

**Comment by wise-east** [comment]
Hi @calebchiam I finally got around to making the updates as you suggested. The drive folder contains the updated dataset and the google doc has been updated with your feedback. Please let me know if you need anything else! Thank you.

**Comment by calebchiam** [comment]
@wise-east Was on vacation, so had to take a pause on this. 

Last bit of info I need from you, what are the sizes of the train and test splits?

**Comment by wise-east** [comment]
Here's the splits: https://github.com/wise-east/spolin 

<table>
<tr><th> data/spolin-train.json</th>
<th> data/spolin-valid.json </th></tr>
<tr><td>

|| yesands| non-yesands|
|--|---:|---:|
|Spontaneanation|10,459|5,587*|
|Cornell|16,426|18,310|
|SubTle|40,303|19,512|
|Total|67,188|43,409|

</td><td>

|| yesands| non-yesands|
|--|---:|---:|
|Spontaneanation|500|500|
|Cornell|500|500|
|Total|1,000|1,000|

</td></tr> </table>

**Comment by calebchiam** [comment]
Thanks for your contribution, @wise-east!

You can now download the SPOLIN corpus through ConvoKit: `Corpus(download('spolin-corpus'))`

Your dataset description can be found here: https://convokit.cornell.edu/documentation/spolin.html

If you want to change the description, you can [edit the file directly](https://github.com/CornellNLP/ConvoKit/blob/master/docs/source/spolin.rst) and make a PR.
