### ISSUE TITLE
How to construct corpus from raw Reddit dataset?

### ISSUE THREAD

**Issue by TaoRuan-Campus** [CornellNLP/ConvoKit#182]
`corpus = Corpus(filename=download("reddit-corpus-small"))`

Could you please give an example of how to construct the Reddit corpus such as"reddit-corpus-small"?

**Comment by calebchiam** [comment]
I don't have a code example for you, but a high level, the construction process was something like:
1. Pick `X` popular subreddits
2. Sample `Y` conversations from each subreddit corpus within a given time period, where each conversation has at least `N` utterances
3. Then take these conversations / utterances and put them in a single corpus.

`reddit-corpus-small` did this with `X=100`, `Y=100` and `N=100`. One peculiarity is that it defines conversations as starting from a top-level comment, whereas in the subreddit corpora themselves, the conversation starts from the Reddit post.
