### ISSUE TITLE
"coordination" jpynb not working for Supreme Court Dataset

### ISSUE THREAD

**Issue by flckv** [CornellNLP/ConvoKit#190]
I downloaded the example file from https://github.com/CornellNLP/ConvoKit/blob/master/examples/coordination/examples.ipynb
I uploaded it to Colab but there is an issue: 

It says " KeyError: 'is-admin'
admins = lambda speaker: speaker.meta["is-admin"]

**Comment by calebchiam** [comment]
Perhaps you're running the wrong sections of the notebook? `is-admin` is only relevant for the `WikiCorpus` example. It won't work for the Supreme Court Dataset.

**Comment by calebchiam** [comment]
Closing this issue since I could not replicate it -- lmk if you still encounter it @flckv
