### ISSUE TITLE
Run Tests locally

### ISSUE THREAD

**Issue by seanzhangkx8** [CornellNLP/ConvoKit#191]
Hi! This is a very quick question. So when I run tests on my local machine following the [contribution guideline](https://github.com/CornellNLP/ConvoKit/blob/master/CONTRIBUTING.md), an Error occurred as:

# Screenshot

<img width="1032" alt="Screenshot 2023-03-01 at 23 17 34" src="https://user-images.githubusercontent.com/106214464/222329937-c074ec34-7513-447b-84f3-260f1bebb3be.png">

So all tests failed because no module named 'convokit.tests' can be found.

# Steps to reproduce

I am using conda, python version 3.9, with convokit installed from the downloaded directory and all requirement-dev installed. Run tests using the command: `cd convokit/tests/ && python run_all_tests.py`

# Additional information

As above. Please let me know how I can solve such issue. Thanks!

**Comment by calebchiam** [comment]
Following the stack trace, it looks like the unittest loader has loaded the installed `convokit` package instead of using the root directory's `convokit` module.

Try running `pip freeze | grep convokit`. What is the output? If it shows `convokit` with a specific version number, that's probably the issue and you should uninstall that in your virtualenv. For reference, mine looks like:

```zsh
(venv) (base) caleb:tests calebchiam$ pip freeze | grep convokit
-e git+https://github.com/CornellNLP/ConvoKit.git@574a0920dfcaa056d3708ff2b2a139ebf89c0a88#egg=convokit
```

**Comment by seanzhangkx8** [comment]
By running `pip freeze | grep convokit`, I got:

`convokit @ file:///Users/--/Desktop/ConvoKit`

I got the same output as yours by installing from github repo. With my result, I used `pip install .` to install from locally downloaded directory. However, neither works when I attempt to run tests. I think both case are not convokit specific version number so that may not be the case.

**Comment by seanzhangkx8** [comment]
I tried reinstall everything by creating a new conda environment. Here is what I did:

> 1. create a new conda env with python==3.9 and download ConvoKit from github

> 2. from downloaded ConvoKit directory, install from root dir by `pip install .`

> 3. follow documentation, install required packages. (nltk.punkt, spacy en_core_web_sm, requirements-dev.txt)

> 4. run cd convokit/tests/ && python run_all_tests.py from downloaded ConvoKit directory

And I still get same error as before. I was wondering

By running  `pip freeze | grep convokit`, I got: `convokit @ file:///Users/--/Desktop/ConvoKit_new`

<img width="870" alt="Screenshot 2023-03-07 at 00 20 29" src="https://user-images.githubusercontent.com/106214464/223327637-a93240a6-d967-4a66-909b-4c944fb71c1b.png">

**Comment by calebchiam** [comment]
It could be that when you invoke `python`, you're not using your virtualenv's version of `python`.

Try running this:
```
python    // to enter the interactive console
import convokit
convokit
```

The last line should return something like `<module 'convokit' from '/Users/calebchiam/Documents/GitHub/Cornell-Conversational-Analysis-Toolkit/convokit/__init__.py'>`.

**Comment by seanzhangkx8** [comment]
my return message is: `<module 'convokit' from '/Users/--/opt/anaconda3/envs/convokit_origin/lib/python3.9/site-packages/convokit/__init__.py'>
`

**Comment by seanzhangkx8** [comment]
I see, that make a lot of sense. I think I solved it and is able to run now. Thank you for the help Caleb!
