### ISSUE TITLE
Complete Subreddits?

### ISSUE THREAD

**Issue by SpaceCowboy850** [CornellNLP/ConvoKit#209]
I'm collecting data for training a language model, and these datasets look amazing.

With the subreddits...I'd like to collect them _all_....but I'm not clear how I would go about doing that.  Is there one (or a handful of ) large zip(s) I could pull?  What is the total size on disk if I were to pull all the subreddits?

**Comment by calebchiam** [comment]
Hi, you can pull from here directly: https://zissou.infosci.cornell.edu/convokit/datasets/subreddit-corpus/corpus-zipped/

It's been a while, but I believe it's several TB
