### ISSUE TITLE
convokit.download is broken when downloading non-Corpus objects

### ISSUE THREAD

**Issue by jpwchang** [CornellNLP/ConvoKit#216]
Theoretically, `convokit.download` supports downloading items other than corpora. For instance, the "official" way to obtain the trained motifs for the Parliament dataset (for use in, say, reproducing QuestionTypology results) is to run `convokit.download('parliament-motifs'). If you actually try to do this, however, you will get an error, because `convokit.download` tries to load an index.json for the target object (which exists for corpora, but not for non-Corpus objects).

# Steps to reproduce

Simply try the following:
```
import convokit
convokit.download("parliament-motifs")
```
And you will see that the download completes successfully but then the function errors out because it attempts to load `index.json` which is nonexistent

# Additional information

I plan to address this issue in my upcoming pull request for the `Forecaster` rewrite, since this bug must be fixed in order to successfully support downloading pretrained Forecaster models.

**Comment by cristiandnm** [comment]
This was fixed in release 3.0.1
