### ISSUE TITLE
Confusing `converting_movie_corpus.ipynb`, is a file missing?

### ISSUE THREAD

**Issue by kakeith** [CornellNLP/ConvoKit#254]
We are trying to follow the tutorial in https://github.com/CornellNLP/ConvoKit/blob/master/examples/converting_movie_corpus.ipynb

We cannot find `movie_conversations.txt` which makes it difficult to follow the tutorial. Can someone please point us to this file or push it? Thanks!

**Comment by seanzhangkx8** [comment]
Hi! The `movie_conversations.txt` file and the corpus can be found [here](https://www.cs.cornell.edu/~cristian/Chameleons_in_imagined_conversations.html), you can click `Legacy dataset` to download. Thanks for pointing this out and I will fix the link in the demo.

**Comment by cristiandnm** [comment]
@kakeith we also have a series of other corpus conversion examples, which you can find under: https://github.com/CornellNLP/ConvoKit/tree/master/examples/dataset-examples

We are also happy to help with any dataset addition on the ConvoKit discord: https://discord.com/invite/WMFqMWgz6P
